version: "3.8"

services:

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/Portugal
    ports:
      - 1880:1880
    networks:
      idc-net:
        ipv4_address: 172.100.10.15
    volumes:
      - ./data/node-red-data:/data
      
  mosquitto:
      image: eclipse-mosquitto:latest
      container_name: mosquitto
      ports:
          - 1883:1883
          - 8883:8883
          - 9001:9001
      volumes:
          - ./data/mosquitto-data/config:/mosquitto/config
          - ./data/mosquitto-data/data:/mosquitto/data
          - ./data/mosquitto-data/log:/mosquitto/log
      networks:
          idc-net:
              ipv4_address: 172.100.10.10

  mysql-db:
    build:
      dockerfile: Dockerfile
      context: data/mysql-data
    container_name: mysql-db
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      idc-net:
        ipv4_address: 172.100.10.18

  web:
      build: ./data/app-data/
      container_name: app
      ports:
        - "8000:8000"
      networks:
          idc-net:
              ipv4_address: 172.100.10.14

  processor:
    build:
      dockerfile: Dockerfile
      context: data/processor-data
    container_name: processor
    restart: always
    ports:
      - "8081:8081"
    networks:
      idc-net:
        ipv4_address: 172.100.10.19

  flutter-web:
    build:
      dockerfile: Dockerfile
      context: data/flutterdata/app
    container_name: flutter-app
    restart: always
    ports:
      - "8082:80"
    networks:
      idc-net:
        ipv4_address: 172.100.10.20

networks:
  idc-net:
      ipam:
        driver: default
        config:
          - subnet: 172.100.10.0/24